attrib -R .\Bam.Net\Bam.Net.nuspec
attrib -R .\Bam.Net.Analytics\Bam.Net.Analytics.nuspec
attrib -R .\Bam.Net.Automation\Bam.Net.Automation.nuspec
attrib -R .\Bam.Net.CommandLine\Bam.Net.CommandLine.nuspec
attrib -R .\Bam.Net.Data\Bam.Net.Data.nuspec
attrib -R .\Bam.Net.Data.Repositories\Bam.Net.Data.Repositories.nuspec
attrib -R .\Bam.Net.Distributed\Bam.Net.Distributed.nuspec
attrib -R .\Bam.Net.Drawing\Bam.Net.Drawing.nuspec
attrib -R .\Bam.Net.Dust\Bam.Net.Dust.nuspec
attrib -R .\Bam.Net.Encryption\Bam.Net.Encryption.nuspec
attrib -R .\Bam.Net.Html\Bam.Net.Html.nuspec
attrib -R .\Bam.Net.Incubation\Bam.Net.Incubation.nuspec
attrib -R .\Bam.Net.Javascript\Bam.Net.Javascript.nuspec
attrib -R .\Bam.Net.Logging\Bam.Net.Logging.nuspec
attrib -R .\Bam.Net.Messaging\Bam.Net.Messaging.nuspec
attrib -R .\Bam.Net.Net\Bam.Net.Net.nuspec
attrib -R .\Bam.Net.Profiguration\Bam.Net.Profiguration.nuspec
attrib -R .\Bam.Net.Schema.Org\Bam.Net.Schema.Org.nuspec
attrib -R .\Bam.Net.Server\Bam.Net.Server.nuspec
attrib -R .\Bam.Net.ServiceProxy\Bam.Net.ServiceProxy.nuspec
attrib -R .\Bam.Net.SourceControl\Bam.Net.SourceControl.nuspec
attrib -R .\Bam.Net.Syndication\Bam.Net.Syndication.nuspec
attrib -R .\Bam.Net.Testing\Bam.Net.Testing.nuspec
attrib -R .\Bam.Net.UserAccounts\Bam.Net.UserAccounts.nuspec
attrib -R .\Bam.Net.Yaml\Bam.Net.Yaml.nuspec
