@echo off
nuver /show:id,version,authors,owners,copyright /path:BamToolkit\BamToolkit.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net\Bam.Net.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Analytics\Bam.Net.Analytics.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Automation\Bam.Net.Automation.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.CommandLine\Bam.Net.CommandLine.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Data\Bam.Net.Data.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Data.Dynamic\Bam.Net.Data.Dynamic.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Data.Repositories\Bam.Net.Data.Repositories.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Distributed\Bam.Net.Distributed.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Drawing\Bam.Net.Drawing.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Dust\Bam.Net.Dust.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Encryption\Bam.Net.Encryption.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Html\Bam.Net.Html.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Incubation\Bam.Net.Incubation.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Javascript\Bam.Net.Javascript.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Logging\Bam.Net.Logging.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Messaging\Bam.Net.Messaging.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Net\Bam.Net.Net.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Profiguration\Bam.Net.Profiguration.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Schema.Org\Bam.Net.Schema.Org.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Server\Bam.Net.Server.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.ServiceProxy\Bam.Net.ServiceProxy.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.SourceControl\Bam.Net.SourceControl.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Syndication\Bam.Net.Syndication.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Testing\Bam.Net.Testing.nuspec 
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.UserAccounts\Bam.Net.UserAccounts.nuspec
nuver /show:id,version,authors,owners,copyright /path:Bam.Net.Yaml\Bam.Net.Yaml.nuspec