{
  "Name": "Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers",
  "WorkerConfs": {
    "two": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+TestWorker, bam.net.automation.core.tests, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 1,
      "Name": "two",
      "Properties": {
        "RequiredProperties": "[]"
      }
    },
    "one": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+TestWorker, bam.net.automation.core.tests, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 0,
      "Name": "one",
      "Properties": {
        "RequiredProperties": "[]"
      }
    }
  },
  "WorkerFiles": [
    "/mnt/chumbucket4/opt/bam/src/repos/Bam.Core/tests/bam.net.automation.core.tests/TestData/JobManagerService_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/two.yaml",
    "/mnt/chumbucket4/opt/bam/src/repos/Bam.Core/tests/bam.net.automation.core.tests/TestData/JobManagerService_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/one.yaml"
  ],
  "JobDirectory": "/mnt/chumbucket4/opt/bam/src/repos/Bam.Core/tests/bam.net.automation.core.tests/TestData/JobManagerService_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers"
}