/*
	Copyright © Bryan Apellanes 2015  
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLGates.Configuration.Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationResponse", Namespace="http://schemas.datacontract.org/2004/07/KLGates.Configuration.Service")]
    public partial class ConfigurationResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private KLGates.Configuration.Service.AppKeyValue[] AppSettingsField;
        
        private string ApplicationNameField;
        
        private KLGates.Configuration.Service.RijndaelKeyVectorPair ClientKeyField;
        
        private string MessageField;
        
        private KLGates.Configuration.Service.ConfigurationResult ResultField;
        
        private string ServerKeyField;
        
        private string SettingKeyField;
        
        private string SettingValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KLGates.Configuration.Service.AppKeyValue[] AppSettings
        {
            get
            {
                return this.AppSettingsField;
            }
            set
            {
                this.AppSettingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName
        {
            get
            {
                return this.ApplicationNameField;
            }
            set
            {
                this.ApplicationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KLGates.Configuration.Service.RijndaelKeyVectorPair ClientKey
        {
            get
            {
                return this.ClientKeyField;
            }
            set
            {
                this.ClientKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KLGates.Configuration.Service.ConfigurationResult Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerKey
        {
            get
            {
                return this.ServerKeyField;
            }
            set
            {
                this.ServerKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingKey
        {
            get
            {
                return this.SettingKeyField;
            }
            set
            {
                this.SettingKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingValue
        {
            get
            {
                return this.SettingValueField;
            }
            set
            {
                this.SettingValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RijndaelKeyVectorPair", Namespace="http://schemas.datacontract.org/2004/07/KLGates.Configuration.Service")]
    public partial class RijndaelKeyVectorPair : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Base64InitializationVectorField;
        
        private string Base64KeyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64InitializationVector
        {
            get
            {
                return this.Base64InitializationVectorField;
            }
            set
            {
                this.Base64InitializationVectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64Key
        {
            get
            {
                return this.Base64KeyField;
            }
            set
            {
                this.Base64KeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppKeyValue", Namespace="http://schemas.datacontract.org/2004/07/KLGates.Configuration.Service")]
    public partial class AppKeyValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationResult", Namespace="http://schemas.datacontract.org/2004/07/KLGates.Configuration.Service")]
    public enum ConfigurationResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeyNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationNotRegistered = 4,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IConfigurationService")]
public interface IConfigurationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetValue", ReplyAction="http://tempuri.org/IConfigurationService/GetValueResponse")]
    KLGates.Configuration.Service.ConfigurationResponse GetValue(string masterEncryptedApplicationHash, string clientEncryptedSettingKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SetValue", ReplyAction="http://tempuri.org/IConfigurationService/SetValueResponse")]
    KLGates.Configuration.Service.ConfigurationResponse SetValue(string masterEncryptedApplicationHash, string encryptedKey, string encryptedValue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetClientKey", ReplyAction="http://tempuri.org/IConfigurationService/GetClientKeyResponse")]
    KLGates.Configuration.Service.ConfigurationResponse GetClientKey(string masterEncryptedApplicationHash, string tempPublicKeyXml);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetServerKey", ReplyAction="http://tempuri.org/IConfigurationService/GetServerKeyResponse")]
    KLGates.Configuration.Service.ConfigurationResponse GetServerKey();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetApplicationSettings", ReplyAction="http://tempuri.org/IConfigurationService/GetApplicationSettingsResponse")]
    KLGates.Configuration.Service.ConfigurationResponse GetApplicationSettings(string masterEncryptedApplicationHash);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetApplicationName", ReplyAction="http://tempuri.org/IConfigurationService/GetApplicationNameResponse")]
    KLGates.Configuration.Service.ConfigurationResponse GetApplicationName(string masterEncryptedApplicationHash);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IConfigurationServiceChannel : IConfigurationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<IConfigurationService>, IConfigurationService
{
    
    public ConfigurationServiceClient()
    {
    }
    
    public ConfigurationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public KLGates.Configuration.Service.ConfigurationResponse GetValue(string masterEncryptedApplicationHash, string clientEncryptedSettingKey)
    {
        return base.Channel.GetValue(masterEncryptedApplicationHash, clientEncryptedSettingKey);
    }
    
    public KLGates.Configuration.Service.ConfigurationResponse SetValue(string masterEncryptedApplicationHash, string encryptedKey, string encryptedValue)
    {
        return base.Channel.SetValue(masterEncryptedApplicationHash, encryptedKey, encryptedValue);
    }
    
    public KLGates.Configuration.Service.ConfigurationResponse GetClientKey(string masterEncryptedApplicationHash, string tempPublicKeyXml)
    {
        return base.Channel.GetClientKey(masterEncryptedApplicationHash, tempPublicKeyXml);
    }
    
    public KLGates.Configuration.Service.ConfigurationResponse GetServerKey()
    {
        return base.Channel.GetServerKey();
    }
    
    public KLGates.Configuration.Service.ConfigurationResponse GetApplicationSettings(string masterEncryptedApplicationHash)
    {
        return base.Channel.GetApplicationSettings(masterEncryptedApplicationHash);
    }
    
    public KLGates.Configuration.Service.ConfigurationResponse GetApplicationName(string masterEncryptedApplicationHash)
    {
        return base.Channel.GetApplicationName(masterEncryptedApplicationHash);
    }
}
