@echo on
call copy_Bam.Net.Data.cmd %1
call copy_BamCore.cmd %1
call copy_Bam.Net.Analytics.cmd %1
call copy_Bam.Net.Automation.cmd %1
call copy_Bam.Net.cmd %1
call copy_Bam.Net.CommandLine.cmd %1
call copy_Bam.Net.CoreServices.cmd %1
call copy_Bam.Net.Data.Dynamic.cmd %1
call copy_Bam.Net.Data.Repositories.cmd %1
call copy_Bam.Net.Documentation.cmd %1
call copy_Bam.Net.Drawing.cmd %1
call copy_Bam.Net.Dust.cmd %1
call copy_Bam.Net.Encryption.cmd %1
call copy_Bam.Net.Html.cmd %1
call copy_Bam.Net.Incubation.cmd %1
call copy_Bam.Net.Javascript.cmd %1
call copy_Bam.Net.Logging.cmd %1
call copy_Bam.Net.Messaging.cmd %1
call copy_Bam.Net.Net.cmd %1
call copy_Bam.Net.Profiguration.cmd %1
call copy_Bam.Net.Schema.Org.cmd %1
call copy_Bam.Net.Server.cmd %1
call copy_Bam.Net.ServiceProxy.cmd %1
call copy_Bam.Net.Syndication.cmd %1
call copy_Bam.Net.Testing.cmd %1
call copy_Bam.Net.UserAccounts.cmd %1
call copy_Bam.Net.Yaml.cmd %1
call copy_Bam.Net.ServiceProxy.Tests.cmd %1
call copy_Bam.cmd %1
