@echo off
call copy_Bam.Net.cmd 
call copy_Bam.Net.Analytics.cmd
call copy_Bam.Net.ApplicationServices.cmd
call copy_Bam.Net.Automation.cmd
call copy_Bam.Net.CommandLine.cmd 
call copy_Bam.Net.Data.cmd
call copy_Bam.Net.Data.Dynamic.cmd
call copy_Bam.Net.Data.Repositories.cmd
call copy_Bam.Net.Distributed.cmd
call copy_Bam.Net.Drawing.cmd
call copy_Bam.Net.Dust.cmd
call copy_Bam.Net.Encryption.cmd
call copy_Bam.Net.Html.cmd
call copy_Bam.Net.Incubation.cmd 
call copy_Bam.Net.Javascript.cmd
call copy_Bam.Net.Logging.cmd 
call copy_Bam.Net.Messaging.cmd
call copy_Bam.Net.Net.cmd
call copy_Bam.Net.Profiguration.cmd
call copy_Bam.Net.Schema.Org.cmd
call copy_Bam.Net.Server.cmd 
call copy_Bam.Net.ServiceProxy.cmd 
call copy_Bam.Net.SourceControl.cmd
call copy_Bam.Net.Syndication.cmd
call copy_Bam.Net.Testing.cmd 
call copy_Bam.Net.UserAccounts.cmd 
call copy_Bam.Net.Yaml.cmd 

