@echo on
nuget push Z:\Workspace\NugetPackages\Push\BamToolkit.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Analytics.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Automation.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.CommandLine.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.CoreServices.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Data.Dynamic.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Data.Repositories.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Distributed.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Documentation.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Drawing.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Dust.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Encryption.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Html.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Incubation.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Javascript.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Logging.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Messaging.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Net.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Profiguration.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Schema.Org.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Server.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.ServiceProxy.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.ServiceProxy.Tests.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.SourceControl.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Syndication.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Testing.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.UserAccounts.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.Yaml.%1.nupkg
nuget push Z:\Workspace\NugetPackages\Push\Bam.Net.ServiceProxy.Tests.%1.nupkg
call git_commit_all.cmd %1
call git_tag_version.cmd %1