using System;

namespace Bam.Net.Schema.Org
{
	///<summary>A Report generated by governmental or non-governmental organization.</summary>
	public class Report: Article
	{
		///<summary>The number or other unique designator assigned to a Report by the publishing organization.</summary>
		public Text ReportNumber {get; set;}
	}
}
