/*
	Copyright © Bryan Apellanes 2015  
*/
using System;

namespace Bam.Net.Schema.Org
{
	///<summary>A service provided by an organization, e.g. delivery service, print services, etc.</summary>
	public class Service: Intangible
	{
		///<summary>A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).</summary>
		public ServiceChannel AvailableChannel {get; set;}
		///<summary>The tangible thing generated by the service, e.g. a passport, permit, etc.</summary>
		public Thing Produces {get; set;}
		///<summary>The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller. Supersedes carrier.</summary>
		public OneOfThese<Person , Organization> Provider {get; set;}
		///<summary>The geographic area where the service is provided.</summary>
		public AdministrativeArea ServiceArea {get; set;}
		///<summary>The audience eligible for this service.</summary>
		public Audience ServiceAudience {get; set;}
		///<summary>The type of service being offered, e.g. veterans' benefits, emergency relief, etc.</summary>
		public Text ServiceType {get; set;}
	}
}
